export const CATEGORIES_ACTION_TYPES = {
    SET_CATEGORIES : 'category/SET_CATEGORIES_MAP',
    FETCH_CATEGORIES_START: 'category/FETCH_CATEGORY_START',
    FETCH_CATEGORIES_SUCCESS: 'category/FETCH_CATEGORY_SUCCESS',
    FETCH_CATEGORIES_FAIL: 'category/FETCH_CATEGORY_FAILED'
};